version: "3"
services:
  backend:
    container_name: apiserver
    build: ./backend
    volumes:
     - ./backend/app/:/app
    ports:
      - "8000:80"
    env_file:
      - ./docker.env
    stdin_open: true
    tty: true
    networks:
      - default
    depends_on:
      - db
  db:
    container_name: dbserver
    build: ./db
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d
      - ./db/data/:/var/lib/postgresql/data
    env_file:
      - ./docker.env
    networks:
      - default
  frontend:
    container_name: webserver
    build: ./frontend
    volumes:
      - ./frontend/app/:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - ./docker.env
    stdin_open: true
    tty: true
    networks:
      - default
networks:
  default: