# Generated by Django 4.2.4 on 2023-08-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0002_alter_loginmodel_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodel',
            old_name='create_datetime',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='loginmodel',
            old_name='update_datetime',
            new_name='updated',
        ),
    ]
